webpackJsonp([1],{

/***/ 147:
/***/ function(module, exports, __webpack_require__) {

	var __vue_script__, __vue_template__
	__webpack_require__(148)
	__vue_script__ = __webpack_require__(149)
	__vue_template__ = __webpack_require__(162)
	module.exports = __vue_script__ || {}
	if (module.exports.__esModule) module.exports = module.exports.default
	if (__vue_template__) { (typeof module.exports === "function" ? module.exports.options : module.exports).template = __vue_template__ }
	if (false) {(function () {  module.hot.accept()
	  var hotAPI = require("vue-hot-reload-api")
	  hotAPI.install(require("vue"), true)
	  if (!hotAPI.compatible) return
	  var id = "E:\\ZxCloud\\src\\components\\rubbishbox.vue"
	  if (!module.hot.data) {
	    hotAPI.createRecord(id, module.exports)
	  } else {
	    hotAPI.update(id, module.exports, __vue_template__)
	  }
	})()}

/***/ },

/***/ 148:
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },

/***/ 149:
/***/ function(module, exports, __webpack_require__) {

	'use strict';
	
	Object.defineProperty(exports, "__esModule", {
	  value: true
	});
	
	var _personalInforTitle = __webpack_require__(15);
	
	var _personalInforTitle2 = _interopRequireDefault(_personalInforTitle);
	
	var _rubbishChoseTitle = __webpack_require__(150);
	
	var _rubbishChoseTitle2 = _interopRequireDefault(_rubbishChoseTitle);
	
	var _rubbishTitle = __webpack_require__(154);
	
	var _rubbishTitle2 = _interopRequireDefault(_rubbishTitle);
	
	var _rubbishList = __webpack_require__(158);
	
	var _rubbishList2 = _interopRequireDefault(_rubbishList);
	
	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
	
	// <style>
	//   /*   @import '../styles/reset.css'; */
	//       /* @import '../styles/Font-Awesome/css/font-awesome.min.css'; */ 
	// </style>
	// <template>
	//     <section  class="main-contant">
	//     <!-- 头部 -->
	//     <personal-infor></personal-infor>
	//
	//
	//     </section>
	//     <section class="main-resource">
	//     	<rubbish-Chose></rubbish-Chose>
	//     	<chose-Title></chose-Title>
	//     	<rubbish-List></rubbish-List>
	//
	//     </section>
	// </template>
	// <script>
	
	exports.default = {
	  store: ['user'],
	  components: {
	    personalInfor: _personalInforTitle2.default,
	    rubbishChose: _rubbishChoseTitle2.default,
	    choseTitle: _rubbishTitle2.default,
	    rubbishList: _rubbishList2.default
	  },
	  ready: function ready() {},
	  data: function data() {
	    return {
	      totalTime: 0
	
	    };
	  },
	
	  events: {}
	};
	// </script>
	//
	/* generated by vue-loader */

/***/ },

/***/ 150:
/***/ function(module, exports, __webpack_require__) {

	var __vue_script__, __vue_template__
	__webpack_require__(151)
	__vue_script__ = __webpack_require__(152)
	__vue_template__ = __webpack_require__(153)
	module.exports = __vue_script__ || {}
	if (module.exports.__esModule) module.exports = module.exports.default
	if (__vue_template__) { (typeof module.exports === "function" ? module.exports.options : module.exports).template = __vue_template__ }
	if (false) {(function () {  module.hot.accept()
	  var hotAPI = require("vue-hot-reload-api")
	  hotAPI.install(require("vue"), true)
	  if (!hotAPI.compatible) return
	  var id = "E:\\ZxCloud\\src\\components\\rubbishChoseTitle.vue"
	  if (!module.hot.data) {
	    hotAPI.createRecord(id, module.exports)
	  } else {
	    hotAPI.update(id, module.exports, __vue_template__)
	  }
	})()}

/***/ },

/***/ 151:
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },

/***/ 152:
/***/ function(module, exports, __webpack_require__) {

	"use strict";
	
	Object.defineProperty(exports, "__esModule", {
	  value: true
	});
	
	var _showmsgbox = __webpack_require__(25);
	
	var _showmsgbox2 = _interopRequireDefault(_showmsgbox);
	
	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
	
	exports.default = {
	  components: {},
	  props: ["titleoperation", "iscreatnewfolder"],
	  ready: function ready() {
	    /*console.log(WebUploader)
	    var uploader = WebUploader.create({ 
	           auto:false, 
	           pick: {
	              id: '#attach',
	              name:"file",  //
	              label: '点击选择图片',
	          },
	          swf: './webUploader/Uploader.swf',  
	          server: "../FileUploadAction",  
	          duplicate:false,//
	          resize: false,
	          compress: null,//
	          chunked: true,  
	          chunkSize: 5 * 1024 * 1024,  
	          chunkRetry:false,
	          threads:1//。
	      });  
	      console.log(uploader)*/
	  },
	  data: function data() {
	    return {
	      mymsg: ""
	    };
	  },
	
	  events: {
	    timeUpdate: function timeUpdate() {}
	  },
	  watch: {},
	  methods: {
	    changekey: function changekey() {
	      this.mymsg = true;
	      this.$broadcast("changekey", this.mymsg);
	    },
	    rename: function rename() {
	      if (!this.titleoperation) {
	
	        this.$dispatch("titleRename");
	      } else {
	        alert('请选择一个文件');
	      }
	    },
	    creatOneFolder: function creatOneFolder() {
	      if (!this.iscreatnewfolder) {
	        this.$dispatch('creatOneFolder');
	      } else {
	        return false;
	      }
	    },
	    exchange: function exchange() {
	      this.$dispatch("exchangeforderfn");
	    }
	  }
	};
	// </script>
	/* generated by vue-loader */
	// <style >/* 网盘操作 */
	//
	// </style>
	// <template>
	// 	<div class="all-buttons main-navs  my-data-select">
	//
	// 	<button type="button"  class="btn btn-default" >全部还原</button>
	//
	// 	<button type="button" class="btn btn-default" :class = "{mydisabled : titleoperation,}" @click="exchange">全部删除</button>
	//
	//
	//
	//
	//
	// </div>
	//
	// </template>
	// <script>

/***/ },

/***/ 153:
/***/ function(module, exports) {

	module.exports = "\r\n\t<div class=\"all-buttons main-navs  my-data-select\">\r\n\t\r\n\t<button type=\"button\"  class=\"btn btn-default\" >全部还原</button>\r\n\r\n\t<button type=\"button\" class=\"btn btn-default\" :class = \"{mydisabled : titleoperation,}\" @click=\"exchange\">全部删除</button>\r\n\r\n\t\r\n\t\r\n\r\n\t\r\n</div>\r\n   \r\n";

/***/ },

/***/ 154:
/***/ function(module, exports, __webpack_require__) {

	var __vue_script__, __vue_template__
	__webpack_require__(155)
	__vue_script__ = __webpack_require__(156)
	__vue_template__ = __webpack_require__(157)
	module.exports = __vue_script__ || {}
	if (module.exports.__esModule) module.exports = module.exports.default
	if (__vue_template__) { (typeof module.exports === "function" ? module.exports.options : module.exports).template = __vue_template__ }
	if (false) {(function () {  module.hot.accept()
	  var hotAPI = require("vue-hot-reload-api")
	  hotAPI.install(require("vue"), true)
	  if (!hotAPI.compatible) return
	  var id = "E:\\ZxCloud\\src\\components\\rubbishTitle.vue"
	  if (!module.hot.data) {
	    hotAPI.createRecord(id, module.exports)
	  } else {
	    hotAPI.update(id, module.exports, __vue_template__)
	  }
	})()}

/***/ },

/***/ 155:
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },

/***/ 156:
/***/ function(module, exports) {

	// <style scoped>
	//   /* 网盘操作 */
	//
	//
	//
	//
	//
	//
	// </style>
	// <template>
	//     <div class="row  main-resource-title" >
	//       <div class=" col-md-1 col-sm-1 col-xs-1">
	//         <input type="checkbox" v-model="allchosekey" @click="mychose">
	//         <span>全选</span>
	//       </div>
	//       <div class=" col-md-4 col-sm-4 col-xs-4">
	//
	//         <p>文件名</p>
	//       </div>
	//       <div class=" col-md-2 col-sm-2 col-xs-2"></div>
	//
	//       <div class=" col-md-3 col-sm-3 col-xs-3">
	//
	//         <p>删除时间</p>
	//       </div>
	//
	//       <div class=" col-md-2 col-sm-2 col-xs-2">
	//
	//         <p>时效</p>
	//       </div>
	//
	//     </div>
	//
	// </template>
	// <script>


	// </script>
	//
	/* generated by vue-loader */
	"use strict";

/***/ },

/***/ 157:
/***/ function(module, exports) {

	module.exports = "\n    <div class=\"row  main-resource-title\" _v-19021f2d=\"\">\n      <div class=\" col-md-1 col-sm-1 col-xs-1\" _v-19021f2d=\"\">\n        <input type=\"checkbox\" v-model=\"allchosekey\" @click=\"mychose\" _v-19021f2d=\"\">\n        <span _v-19021f2d=\"\">全选</span>\n      </div>\n      <div class=\" col-md-4 col-sm-4 col-xs-4\" _v-19021f2d=\"\">\n\n        <p _v-19021f2d=\"\">文件名</p>\n      </div>\n      <div class=\" col-md-2 col-sm-2 col-xs-2\" _v-19021f2d=\"\"></div>\n\n      <div class=\" col-md-3 col-sm-3 col-xs-3\" _v-19021f2d=\"\">\n\n        <p _v-19021f2d=\"\">删除时间</p>\n      </div>\n\n      <div class=\" col-md-2 col-sm-2 col-xs-2\" _v-19021f2d=\"\">\n\n        <p _v-19021f2d=\"\">时效</p>\n      </div>\n\n    </div>\n\n";

/***/ },

/***/ 158:
/***/ function(module, exports, __webpack_require__) {

	var __vue_script__, __vue_template__
	__webpack_require__(159)
	__vue_script__ = __webpack_require__(160)
	__vue_template__ = __webpack_require__(161)
	module.exports = __vue_script__ || {}
	if (module.exports.__esModule) module.exports = module.exports.default
	if (__vue_template__) { (typeof module.exports === "function" ? module.exports.options : module.exports).template = __vue_template__ }
	if (false) {(function () {  module.hot.accept()
	  var hotAPI = require("vue-hot-reload-api")
	  hotAPI.install(require("vue"), true)
	  if (!hotAPI.compatible) return
	  var id = "E:\\ZxCloud\\src\\components\\rubbishList.vue"
	  if (!module.hot.data) {
	    hotAPI.createRecord(id, module.exports)
	  } else {
	    hotAPI.update(id, module.exports, __vue_template__)
	  }
	})()}

/***/ },

/***/ 159:
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },

/***/ 160:
/***/ function(module, exports) {

	// <style >
	//
	// </style>
	// <template>
	//   <div class="main-resource-data clearfix">
	//     <!-- 文件 -->
	//     <template v-for="mydata in datas" :fileId="mydata.fileId" :folderId="mydata.folderId"  v-el:fild >
	//       <div class="row main-resource-row-data" >
	//         <div class=" col-md-1 col-sm-1 col-xs-1">
	//           <input type="checkbox" v-model="choseArr"  :value="$index" @click.stop=""></div>
	//         <div class=" col-md-3 col-sm-3 col-xs-3">
	//
	//           <p>
	//             <strong   :class="{'fileIcon':!mydata.fileId}" alt=""></strong>
	//
	//           </p>
	//         </div>
	//
	//           <div class=" col-md-3 col-sm-3 col-xs-3" > 
	//              <div class="contral-icons" v-show="isshowicon">
	//
	//                <i class="icon-reply" @click.stop="renameFolder( mydata,$index)" :class="{disabledIcon: isdisabledIcon}"></i>
	//                <i class="icon-trash" @click.stop="trashFiled(mydata.fileId,$index)"></i>
	//           </div>
	//         </div>
	//         <div class=" col-md-3 col-sm-3 col-xs-3">
	//
	//           <p>{{ mydata.createTime }}</p>
	//         </div>
	//
	//         <div class=" col-md-2 col-sm-2 col-xs-2">
	//
	//           <p>---</p>
	//         </div>
	//
	//         <div class="clearfix visible-xs"></div>
	//
	//       </div>
	//     </template>
	//     <!-- 文件夹 -->
	//     <!-- <div v-for="mydatas in childFolders"   track-by="$index"  track-by="folderId">
	//       <div class="row main-resource-row-data" >
	//         <div class=" col-md-1 col-sm-1 col-xs-1">
	//           <input type="checkbox" v-model="ischoseAllKey"></div>
	//         <div class=" col-md-3 col-sm-3 col-xs-3">
	//
	//           <p>
	//             <img src="../img/fil.png" alt="图片">
	//             <span> <b v-show="!mydatas.isfolderIsShowNameKey">{{ mydatas.name  }}</b> <em v-show="mydatas.isfolderIsShowNameKey "><input type="text"  v-model = "myinputValue">
	//
	//                 <button @click="oktrenameFolder(mydatas.folderId,$index)">✔</button>
	//                 <button @click="notrenameFolder($index)">X</button></em> 
	//             </span>
	//           </p>
	//         </div>
	//
	//         <div class=" col-md-3 col-sm-3 col-xs-3"  >
	//             <div class="contral-icons"  v-show="isshowicon">
	//             <i class="icon-download-alt"></i>
	//             <i class="icon-exchange"></i>
	//             <i class="icon-edit" @click="renameFolder(mydatas,mydatas.name,$index)"></i>
	//             <i class="icon-trash" @click="trashFolder(mydatas.folderId)"></i>
	//         </div>
	//       </div>
	//         <div class=" col-md-3 col-sm-3 col-xs-3">
	//
	//           <p>{{ mydatas.createTime }}</p>
	//         </div>
	//
	//         <div class=" col-md-2 col-sm-2 col-xs-2">
	//
	//           <p>---</p>
	//         </div>
	//
	//         <div class="clearfix visible-xs"></div>
	//
	//       </div>
	//     </div> -->
	//
	//   </div>
	//
	//
	// </template>
	// <script>
	/*import '../js/limitHeight.js';
	
	 


	  export default {
	    components: { 
	          },
	     data () {
	      return {
	         datas: [{"fileId":"d011d344-0a59-44a8-805d-f20d3a2a4d1d","createTime":"2016-08-19 12:55:48","testProperty":"","folderId":"ae7e24b3-dbff-44ed-b6ea-458b15a8782d"},{"fileId":"d011d344-0a59-44a8-805d-f20d3a2a4d1d","createTime":"2016-08-19 12:55:48","testProperty":"","folderId":"ae7e24b3-dbff-44ed-b6ea-458b15a8782d"}],//总数据
	         files: [],//文件
	         childFolders: [],//文件夹`

	         myinputValue: null,//修改name 的value
	         isshowicon: true, //是否修改name
	         folderId: null,// 修改名字的文件夹Id
	         mydatas: null,//数组中的单个文件
	         isdisabledIcon: false,//禁止使用重命名
	         choseArr:[],//单选数组
	         iscreatNewfolder:false,

	         ///////////////////////没有重置////////////////////
	         istreeshow:true,//文件树显示
	         showchange:'hidden'


	        

	      }
	    },
	    store: ['user'],
	    
	    props:[
	          'mychosekey',//全选
	          "listoperation",
	          "isdatecreatnewfolder",
	    ],

	    ready() {

	      this.getresource(this.user.name)
	      

	        var height =  $(window).height() - $('.main-contant').outerHeight(true) - $(".breadcrumb").outerHeight(true) - $(".main-resource-title").outerHeight(true) - $(".my-data-select").outerHeight(true) 
	            
	            $('.main-resource-data').slimscroll({
	                          height: height,
	                          width: 'auto', //可滚动区域宽度
	                          size: '8px', //组件宽度
	                          opacity: .3, //滚动条透明度
	                          distance: '0px', //组件与侧边之间的距离
	                          railColor: '#333', //轨道颜色
	                          railOpacity: .2, //轨道透明度
	                          railDraggable: true, //是否 滚动条可拖动
	                  });

	     

	    },

	  
	   
	    events: {
	      choseButtonClik (value) {
	        this.choseAllinput(value)
	       
	      },

	      titleRename(){
	        //重命名
	        if(this.choseArr.length === 0){
	          alert("请选择一个文件")
	          return false
	        }else{
	          let index = this.choseArr[0]
	          let mydatas  = this.datas[index]
	           this.renameFolder( mydatas,index )
	          
	        }
	      
	       },

	       
	      
	    

	    
	    },
	    methods: {
	      getresource( folderId ){
	          console.log(this.user.name); // logs: 'cody'
	         

	//////////////////////////////修改name到app.vue/////////////////////////////////////

	        
	        this.$http.get('./FolderAction!GetFolderCotent?curFolderId='+folderId)
	          .then(function(ret) {
	              this.datas = JSON.parse(ret.data).files.concat(JSON.parse(ret.data).childFolders);
	              
	              this.files =  JSON.parse(ret.data).files;  
	              this.childFolders = JSON.parse(ret.data).childFolders;
	             
	            
	          })
	          .then(function(err) {
	           
	          })
	      },
	      //删除文件
	      trashFiled (fileId,index){
	          let r=confirm("您确定要删除文件吗")
	            if (r==true)
	              {
	              }
	               else
	              {
	               
	              return false
	              }
	            

	         this.$http.get('./FileInFolderAction!DeleteFile?id='+fileId)
	          .then(function(ret) {
	            console.log(ret) 
	            this.files.splice(index,1)
	          })
	          .then(function(err) {
	            console.log(err);
	          })

	     
	      },
	 

	      //删除文件夹
	      trashFolder (folderId){
	        alert('no use')
	      },
	  

	    /////////////////////////////////////////////////////////////////////////

	      //全选按钮操作
	      choseAllinput(value) {
	          if( false === value){
	            for (var i = 0; i < this.datas.length; i++){
	              if(!this.choseArr.includes(i)){
	                this.choseArr.push(i)
	              }
	              
	            }
	          }else{
	           this.choseArr.splice(0,this.choseArr.length)

	          }
	      },


	    },
	    watch:{
	      choseArr(){
	        if((this.choseArr.length === this.datas.length) && this.choseArr.length != 0 ){
	           //执行全选
	           this.mychosekey =true
	         }else{
	           this.mychosekey =false

	         }

	         //控制移动和重命名的按钮
	        //取消移动和重命名的操作
	        //重命名图标操作
	         if(this.choseArr.length > 1){
	         this.listoperation= true
	         this.isdisabledIcon = true
	         }else{
	           this.listoperation= false
	           this.isdisabledIcon = false
	         }

	      },




	    },

	}
	  
	// </script>*/
	/* generated by vue-loader */
	"use strict";

/***/ },

/***/ 161:
/***/ function(module, exports, __webpack_require__) {

	module.exports = "\r\n  <div class=\"main-resource-data clearfix\">\r\n    <!-- 文件 -->\r\n    <template v-for=\"mydata in datas\" :fileId=\"mydata.fileId\" :folderId=\"mydata.folderId\"  v-el:fild >\r\n      <div class=\"row main-resource-row-data\" >\r\n        <div class=\" col-md-1 col-sm-1 col-xs-1\">\r\n          <input type=\"checkbox\" v-model=\"choseArr\"  :value=\"$index\" @click.stop=\"\"></div>\r\n        <div class=\" col-md-3 col-sm-3 col-xs-3\">\r\n\r\n          <p>\r\n            <strong   :class=\"{'fileIcon':!mydata.fileId}\" alt=\"\"></strong>\r\n             \r\n          </p>\r\n        </div>\r\n       \r\n          <div class=\" col-md-3 col-sm-3 col-xs-3\" > \r\n             <div class=\"contral-icons\" v-show=\"isshowicon\">\r\n               \r\n               <i class=\"icon-reply\" @click.stop=\"renameFolder( mydata,$index)\" :class=\"{disabledIcon: isdisabledIcon}\"></i>\r\n               <i class=\"icon-trash\" @click.stop=\"trashFiled(mydata.fileId,$index)\"></i>\r\n          </div>\r\n        </div>\r\n        <div class=\" col-md-3 col-sm-3 col-xs-3\">\r\n\r\n          <p>{{ mydata.createTime }}</p>\r\n        </div>\r\n\r\n        <div class=\" col-md-2 col-sm-2 col-xs-2\">\r\n\r\n          <p>---</p>\r\n        </div>\r\n\r\n        <div class=\"clearfix visible-xs\"></div>\r\n\r\n      </div>\r\n    </template>\r\n    <!-- 文件夹 -->\r\n    <!-- <div v-for=\"mydatas in childFolders\"   track-by=\"$index\"  track-by=\"folderId\">\r\n      <div class=\"row main-resource-row-data\" >\r\n        <div class=\" col-md-1 col-sm-1 col-xs-1\">\r\n          <input type=\"checkbox\" v-model=\"ischoseAllKey\"></div>\r\n        <div class=\" col-md-3 col-sm-3 col-xs-3\">\r\n    \r\n          <p>\r\n            <img src=\"" + __webpack_require__(126) + "\" alt=\"图片\">\r\n            <span> <b v-show=\"!mydatas.isfolderIsShowNameKey\">{{ mydatas.name  }}</b> <em v-show=\"mydatas.isfolderIsShowNameKey \"><input type=\"text\"  v-model = \"myinputValue\">\r\n    \r\n                <button @click=\"oktrenameFolder(mydatas.folderId,$index)\">✔</button>\r\n                <button @click=\"notrenameFolder($index)\">X</button></em> \r\n            </span>\r\n          </p>\r\n        </div>\r\n    \r\n        <div class=\" col-md-3 col-sm-3 col-xs-3\"  >\r\n            <div class=\"contral-icons\"  v-show=\"isshowicon\">\r\n            <i class=\"icon-download-alt\"></i>\r\n            <i class=\"icon-exchange\"></i>\r\n            <i class=\"icon-edit\" @click=\"renameFolder(mydatas,mydatas.name,$index)\"></i>\r\n            <i class=\"icon-trash\" @click=\"trashFolder(mydatas.folderId)\"></i>\r\n        </div>\r\n      </div>\r\n        <div class=\" col-md-3 col-sm-3 col-xs-3\">\r\n    \r\n          <p>{{ mydatas.createTime }}</p>\r\n        </div>\r\n    \r\n        <div class=\" col-md-2 col-sm-2 col-xs-2\">\r\n    \r\n          <p>---</p>\r\n        </div>\r\n    \r\n        <div class=\"clearfix visible-xs\"></div>\r\n    \r\n      </div>\r\n    </div> -->\r\n\r\n  </div>\r\n \r\n\r\n";

/***/ },

/***/ 162:
/***/ function(module, exports) {

	module.exports = "\r\n    <section  class=\"main-contant\">\r\n    <!-- 头部 -->\r\n    <personal-infor></personal-infor>\r\n\r\n      \r\n    </section>\r\n    <section class=\"main-resource\">\r\n    \t<rubbish-Chose></rubbish-Chose>\r\n    \t<chose-Title></chose-Title>\r\n    \t<rubbish-List></rubbish-List>\r\n\r\n    </section>\r\n";

/***/ }

});
//# sourceMappingURL=1.chunk.js.map